/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alejandro_e4_dimensionlocation;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;

/**
 *
 * @author Alejandro Campos Maestre
 */
public class fraVentana extends javax.swing.JFrame
{

    Dimension Tmonitor = Toolkit.getDefaultToolkit().getScreenSize();
    int ancho = Tmonitor.width;
    int largo = Tmonitor.height;

    String tituloAlig = "center";
    String tituloDim = "300";

    /**
     * Creates new form fraVentana
     */
    public fraVentana()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnArribaDcha = new javax.swing.JButton();
        btnArribaIzq = new javax.swing.JButton();
        btnAbajoIzq = new javax.swing.JButton();
        btnAbajoDcha = new javax.swing.JButton();
        tglDimension = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dimensiones y posiciones – Centro – 300×300");
        setLocation(new java.awt.Point(400, 200));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(300, 300));
        setSize(new java.awt.Dimension(300, 300));

        btnArribaDcha.setText("Arriba Derecha");
        btnArribaDcha.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnArribaDchaActionPerformed(evt);
            }
        });

        btnArribaIzq.setText("Arriba Izquierda");
        btnArribaIzq.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnArribaIzqActionPerformed(evt);
            }
        });

        btnAbajoIzq.setText("Abajo Izquierda");
        btnAbajoIzq.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAbajoIzqActionPerformed(evt);
            }
        });

        btnAbajoDcha.setText("Abajo Derecha");
        btnAbajoDcha.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAbajoDchaActionPerformed(evt);
            }
        });

        tglDimension.setText("Aumenta dimensión");
        tglDimension.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                tglDimensionItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAbajoIzq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAbajoDcha))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnArribaIzq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(btnArribaDcha)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tglDimension)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnArribaIzq)
                    .addComponent(btnArribaDcha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(tglDimension)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbajoDcha)
                    .addComponent(btnAbajoIzq))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArribaIzqActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnArribaIzqActionPerformed
    {//GEN-HEADEREND:event_btnArribaIzqActionPerformed
        // TODO add your handling code here:
        setLocation(0, 0);
        tituloAlig = "Arriba Izquierda";
        this.setTitle("Dimensiones y posiciones – " + tituloAlig + " – " + tituloDim);
    }//GEN-LAST:event_btnArribaIzqActionPerformed

    private void btnArribaDchaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnArribaDchaActionPerformed
    {//GEN-HEADEREND:event_btnArribaDchaActionPerformed
        // TODO add your handling code here:
        setLocation(ancho - 300, 0);
        tituloAlig = "Arriba Derecha";
        this.setTitle("Dimensiones y posiciones – " + tituloAlig + " – " + tituloDim);
    }//GEN-LAST:event_btnArribaDchaActionPerformed

    private void btnAbajoIzqActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAbajoIzqActionPerformed
    {//GEN-HEADEREND:event_btnAbajoIzqActionPerformed
        // TODO add your handling code here:
        setLocation(0, largo - 380);
        tituloAlig = "Abajo Izquierda";
        this.setTitle("Dimensiones y posiciones – " + tituloAlig + " – " + tituloDim);
    }//GEN-LAST:event_btnAbajoIzqActionPerformed

    private void btnAbajoDchaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAbajoDchaActionPerformed
    {//GEN-HEADEREND:event_btnAbajoDchaActionPerformed
        // TODO add your handling code here:
        setLocation(ancho - 300, largo - 380);
        tituloAlig = "Abajo Derecha";
        this.setTitle("Dimensiones y posiciones – " + tituloAlig + " – " + tituloDim);
    }//GEN-LAST:event_btnAbajoDchaActionPerformed

    private void tglDimensionItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_tglDimensionItemStateChanged
    {//GEN-HEADEREND:event_tglDimensionItemStateChanged
        // TODO add your handling code here:
        int estado = evt.getStateChange();
        if (estado == ItemEvent.SELECTED)
        {
            this.tglDimension.setText("Disminuye dimensión");
            this.setSize(600, 600);
            tituloDim = "600x600";
            this.setTitle("Dimensiones y posiciones – " + tituloAlig + " – " + tituloDim);
            ancho = ancho - 300;
            largo = largo - 300;
        } else
        {
            this.tglDimension.setText("Aumenta dimensión");
            this.setSize(300, 300);
            tituloDim = "300x300";
            this.setTitle("Dimensiones y posiciones – " + tituloAlig + " – " + tituloDim);
            ancho = ancho + 300;
            largo = largo + 300;
        }
    }//GEN-LAST:event_tglDimensionItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(fraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(fraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(fraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(fraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new fraVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbajoDcha;
    private javax.swing.JButton btnAbajoIzq;
    private javax.swing.JButton btnArribaDcha;
    private javax.swing.JButton btnArribaIzq;
    private javax.swing.JToggleButton tglDimension;
    // End of variables declaration//GEN-END:variables
}
